name: 'eslint-remote-tester PR comparator'
description: 'Run eslint-remote-tester in comparison mode for pull requests'
author: 'Ari Perkkio <ari.perkkio@gmail.com>'

branding:
  icon: 'git-pull-request'
  color: 'orange'

inputs:
  eslint-remote-tester-config:
    description: 'Path to eslint-remote-tester.config.js'
    required: false
    default: 'eslint-remote-tester.config.js'
  github-token:
    description: 'GitHub token'
    required: false
    default: ${{ github.token }}
  repository-initialize-command:
    description: 'Command used to initialize project after checkout'
    required: false
    default: 'yarn install'
  allowed-associations:
    description: Comment author associations allowed (e.g. '["OWNER", "COLLABORATOR"]')
    required: false
    default: '["OWNER"]'
  max-result-count:
    description: Maximum result count to be posted in result comment. Can be override with maxResultCount option in comment.
    required: false
    default: 50

runs:
  using: 'docker'
  image: 'Dockerfile'
